In [1]:
# Tratamiento de datos
import pandas as pd
# Ignorar warnings
import warnings
warnings.filterwarnings("ignore")
# Configuración
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames
#importar la biblioteca de numpy:
import numpy as np
import os
import sys #permite navegar por el sistema
sys.path.append("../") #solo aplica al soporte
import src.soporte_EDA as se


pd.options.display.float_format = '{:.2f}'.format # para redondearlo todo a 2 decimales

## Limpieza diccionario datos

In [2]:
df_diccionario_datos = pd.read_csv("../datos/raw/diccionario_datos.csv" , sep=';', encoding='latin-1')

In [3]:
df_diccionario_datos

,COLUNA,Unnamed: 1,DESCRIÇÃO,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,Código Órgão Superior,NaN,Código do Órgão Superior responsável pela rece...,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,Nome do Órgão Superior responsável pela receita.,NaN
4,Nome Órgão Superior,NaN,NaN,NaN
...,...,...,...,...
61,Data Lançamento,NaN,Data de lançamento da receita,NaN
62,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN
64,Exercício,NaN,Exercício a que se referem os valores,NaN
65,NaN,NaN,NaN,NaN

In [4]:
se.reporte(df_diccionario_datos)

La tabla tiene 66 filas y 4 columnas
La tabla tiene 30 filas duplicadas

,tipo_variables,contador_total,numero_nulos,porcentaje_nulos,valores_unicos,duplicados
COLUNA,object,16,50,75.76,16,49
Unnamed: 1,float64,0,66,100.00,0,65
DESCRIÇÃO,object,36,30,45.45,30,35
Unnamed: 3,object,14,52,78.79,12,53

In [5]:
df_diccionario_datos = df_diccionario_datos.drop('Unnamed: 1', axis=1)

In [6]:
df_diccionario_datos

,COLUNA,DESCRIÇÃO,Unnamed: 3
0,NaN,NaN,NaN
1,Código Órgão Superior,Código do Órgão Superior responsável pela rece...,NaN
2,NaN,NaN,NaN
3,NaN,Nome do Órgão Superior responsável pela receita.,NaN
4,Nome Órgão Superior,NaN,NaN
...,...,...,...
61,Data Lançamento,Data de lançamento da receita,NaN
62,NaN,NaN,NaN
63,NaN,NaN,NaN
64,Exercício,Exercício a que se referem os valores,NaN
65,NaN,NaN,NaN

In [7]:
df_diccionario_datos.iloc[(4,1)] = df_diccionario_datos.iloc[(3,1)]
df_diccionario_datos.iloc[(3,1)] = np.nan

In [8]:
df_diccionario_datos

,COLUNA,DESCRIÇÃO,Unnamed: 3
0,NaN,NaN,NaN
1,Código Órgão Superior,Código do Órgão Superior responsável pela rece...,NaN
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,Nome Órgão Superior,Nome do Órgão Superior responsável pela receita.,NaN
...,...,...,...
61,Data Lançamento,Data de lançamento da receita,NaN
62,NaN,NaN,NaN
63,NaN,NaN,NaN
64,Exercício,Exercício a que se referem os valores,NaN
65,NaN,NaN,NaN

In [9]:
indices_eliminar = df_diccionario_datos[df_diccionario_datos.COLUNA.isnull()][df_diccionario_datos.DESCRIÇÃO.isnull()].index
indices_eliminar

Index([ 0,  2,  3,  5,  7,  9, 12, 13, 15, 17, 18, 20, 29, 38, 39, 41, 43, 45,
       46, 48, 49, 51, 52, 56, 57, 59, 60, 62, 63, 65],
      dtype='int64')

In [10]:
df_diccionario_datos = df_diccionario_datos.drop(indices_eliminar, axis=0) # eliminar filas con todo nulos
df_diccionario_datos = df_diccionario_datos.drop_duplicates() #eliminar duplicados

In [11]:
df_diccionario_datos.loc[(21,'Unnamed: 3')] = df_diccionario_datos.loc[(21,'DESCRIÇÃO')]
df_diccionario_datos.loc[(30,'Unnamed: 3')] = df_diccionario_datos.loc[(30,'DESCRIÇÃO')]

In [12]:
df_descriptivos_columnas = df_diccionario_datos[df_diccionario_datos.DESCRIÇÃO.notnull()][df_diccionario_datos['Unnamed: 3'].isnull()]

In [13]:
display(df_descriptivos_columnas[['COLUNA','DESCRIÇÃO']])

diccionario_detalle_descripción={}
for indice,detalle in enumerate(df_descriptivos_columnas.DESCRIÇÃO.items()):
    diccionario_detalle_descripción.update({indice:detalle})

# Diccionario de traducción manual
traducciones = {
    'Código do Órgão Superior responsável pela receita.': 'Código del Órgano Superior responsable de la recaudación.',
    'Nome do Órgão Superior responsável pela receita.': 'Nombre del Órgano Superior responsable de la recaudación.',
    'Código do Órgão Subordinado responsável pela receita.': 'Código del Órgano Subordinado responsable de la recaudación.',
    'Nome do Órgão Subordinado responsável pela receita.': 'Nombre del Órgano Subordinado responsable de la recaudación.',
    'Código da Unidade Gestora responsável pela receita.': 'Código de la Unidad Gestora responsable de la recaudación.',
    'UNIDADE GESTORA (UG) - Unidade Orçamentária ou Administrativa que realiza atos de gestão orçamentária, financeira e/ou patrimonial, cujo titular, em consequência, está sujeito a tomada de contas anual na conformidade do disposto nos artigos 81 e 82 do Decreto-lei nr. 200, de 25 de fevereiro de 1967.': 'UNIDAD GESTORA (UG) - Unidad Presupuestaria o Administrativa que realiza actos de gestión presupuestaria, financiera y/o patrimonial, cuyo titular, en consecuencia, está sujeto a rendir cuentas anuales de acuerdo con lo dispuesto en los artículos 81 y 82 del Decreto-Ley nº 200, de 25 de febrero de 1967.',
    '\xa0Nome da Unidade Gestora responsável pela receita.': 'Nombre de la Unidad Gestora responsable de la recaudación.',
    '\xa0\x93Receitas Correntes\x94 ou \x93Receitas de Capital\x94': '"Ingresos Corrientes" o "Ingresos de Capital"',
    'Detalhamento das categorias econômicas Receitas Correntes e Receitas de Capital, com vistas a identificar a procedência das receitas no momento em que ingressam nos cofres públicos. \xa0': 'Desglose de las categorías económicas de los Ingresos Corrientes y de Capital, con el objetivo de identificar el origen de los ingresos al momento de su ingreso en las arcas públicas.',
    'Para \x93Receitas Correntes\x94:': 'Para "Ingresos Corrientes":',
    'Para \x93Receitas de Capital\x94:': 'Para "Ingresos de Capital":',
    'Nível de classificação vinculado à origem, permite qualificar com maior detalhe o fato gerador das receitas. Por exemplo, dentro da origem \x93Contribuições\x94, identificam-se as espécies \x93Contribuições Sociais\x94, \x93Contribuições Econômicas\x94 e \x93Contribuições para Entidades Privadas de Serviço Social e de Formação Profissional\x94.': 'Nivel de clasificación vinculado al origen, permite detallar con mayor precisión el hecho generador de los ingresos. Por ejemplo, dentro del origen "Contribuciones", se identifican las especies "Contribuciones Sociales", "Contribuciones Económicas" y "Contribuciones a Entidades Privadas de Servicio Social y Formación Profesional".',
    'Detalhamento de outros níveis da receita': 'Desglose de otros niveles de la recaudación',
    'Orçamento inicial da receita atualizado por mudanças na previsão': 'Presupuesto inicial de los ingresos actualizado por cambios en la previsión.',
    'Valor da receita lançada': 'Valor de los ingresos registrados.',
    'Data de lançamento da receita': 'Fecha de registro de la recaudación.',
    'Exercício a que se referem os valores': 'Ejercicio al que se refieren los valores.',
    'A tabela-resumo com os códigos relacionados às\xa0origens\xa0e\xa0espécies\xa0de receitas encontra-se no item 8.1.3. do Manual Técnico de Orçamento.': 'La tabla resumen con los códigos relacionados con los orígenes y especies de ingresos se encuentra en el ítem 8.1.3 del Manual Técnico de Presupuesto.',
    'Valor resultado da fase de arrecadação/recolhimento da receita.': 'Valor resultante de la fase de recaudación/recolecta de los ingresos.',
    'Na fase da arrecadação, é feita a entrega, pelos contribuintes ou devedores, dos valores devidos ao Governo. Os valores são entregues aos agentes arrecadadores ou bancos autorizados.': 'En la fase de recaudación, los contribuyentes o deudores entregan los valores adeudados al Gobierno. Los valores se entregan a los agentes recaudadores o bancos autorizados.',
    'O recolhimento consiste na entrega dos valores arrecadados, pelos agentes arrecadadores ou bancos autorizados, aos cofres públicos, tornando-os disponíveis na conta única do Tesouro Nacional, para uso pelo Governo.':'La recolección consiste en la entrega de los valores recaudados, por los agentes recaudadores o bancos autorizados, a las arcas públicas, poniéndolos a disposición en la cuenta única del Tesoro Nacional, para su uso por parte del Gobierno.',
    'Valor Arrecadado/ Valor Previsto *100': 'Valor Recaudado/Valor Previsto *100'

}

# Crear un nuevo diccionario con las traducciones
diccionario_traducido = {}
for key, value in diccionario_detalle_descripción.items():
    indice, texto = value
    # Buscar la traducción en el diccionario
    texto_traducido = traducciones.get(texto, texto)  # Si no encuentra traducción, mantiene el original
    diccionario_traducido[key] = (indice, texto_traducido)

# Mostrar el diccionario traducido
print(f'El descriptivo de las columnas es:')
for key, value in diccionario_traducido.items():
    print(f"{df_descriptivos_columnas.iloc[key,0]}: {value}")
    print()

print(f'Las categorias de recetas corrientes y recetas de capital son:')
df_categorias_recetas_corrientes_y_capital= df_diccionario_datos[df_diccionario_datos.DESCRIÇÃO.notnull()][df_diccionario_datos['Unnamed: 3'].notnull()]
df_categorias_recetas_corrientes_y_capital[['DESCRIÇÃO','Unnamed: 3']]

                     COLUNA                                          DESCRIÇÃO
1     Código Órgão Superior  Código do Órgão Superior responsável pela rece...
4       Nome Órgão Superior   Nome do Órgão Superior responsável pela receita.
6              Código Órgão  Código do Órgão Subordinado responsável pela r...
8                Nome Órgão  Nome do Órgão Subordinado responsável pela rec...
10   Código Unidade Gestora  Código da Unidade Gestora responsável pela rec...
11                      NaN  UNIDADE GESTORA (UG) - Unidade Orçamentária ou...
14     Nome Unidade Gestora   Nome da Unidade Gestora responsável pela rece...
16      Categoria Econômica      Receitas Correntes ou Receitas de Capital
19                   Origem  Detalhamento das categorias econômicas Receita...
40                  Espécie  Nível de classificação vinculado à origem, per...
42                      NaN  A tabela-resumo com os códigos relacionados às...
44             Detalhamento           Detalhamento de outros níveis da receita
47           Valor Previsto  Orçamento inicial da receita atualizado por mu...
50            Valor Lançado                           Valor da receita lançada
53          Valor Realizado  Valor resultado da fase de arrecadação/recolhi...
54                      NaN  Na fase da arrecadação, é feita a entrega, pel...
55                      NaN  O recolhimento consiste na entrega dos valores...
58     Percentual Realizado              Valor Arrecadado/ Valor Previsto *100
61          Data Lançamento                      Data de lançamento da receita
64                Exercício              Exercício a que se referem os valores

El descriptivo de las columnas es:
 Código Órgão Superior: (1, 'Código del Órgano Superior responsable de la recaudación.')

 Nome Órgão Superior: (4, 'Nombre del Órgano Superior responsable de la recaudación.')

 Código Órgão: (6, 'Código del Órgano Subordinado responsable de la recaudación.')

 Nome Órgão: (8, 'Nombre del Órgano Subordinado responsable de la recaudación.')

 Código Unidade Gestora: (10, 'Código de la Unidad Gestora responsable de la recaudación.')

nan: (11, 'UNIDAD GESTORA (UG) - Unidad Presupuestaria o Administrativa que realiza actos de gestión presupuestaria, financiera y/o patrimonial, cuyo titular, en consecuencia, está sujeto a rendir cuentas anuales de acuerdo con lo dispuesto en los artículos 81 y 82 del Decreto-Ley nº 200, de 25 de febrero de 1967.')

 Nome Unidade Gestora: (14, 'Nombre de la Unidad Gestora responsable de la recaudación.')

Categoria Econômica: (16, '"Ingresos Corrientes" o "Ingresos de Capital"')

Origem: (19, 'Desglose de las categorías económicas de los Ingresos Corrientes y de Capital, con el objetivo de identificar el origen de los ingresos al momento de su ingreso en las arcas públicas.')

Espécie: (40, 'Nivel de clasificación vinculado al origen, permite detallar con mayor precisión el hecho generador de los ingresos. Por ejemplo, dentro del origen "Contribuciones", se identifican las especies "Contribuciones Sociales", "Contribuciones Económicas" y "Contribuciones a Entidades Privadas de Servicio Social y Formación Profesional".')

nan: (42, 'La tabla resumen con los códigos relacionados con los orígenes y especies de ingresos se encuentra en el ítem 8.1.3 del Manual Técnico de Presupuesto.')

Detalhamento: (44, 'Desglose de otros niveles de la recaudación')

Valor Previsto: (47, 'Presupuesto inicial de los ingresos actualizado por cambios en la previsión.')

Valor Lançado: (50, 'Valor de los ingresos registrados.')

Valor Realizado: (53, 'Valor resultante de la fase de recaudación/recolecta de los ingresos.')

nan: (54, 'En la fase de recaudación, los contribuyentes o deudores entregan los valores adeudados al Gobierno. Los valores se entregan a los agentes recaudadores o bancos autorizados.')

nan: (55, 'La recolección consiste en la entrega de los valores recaudados, por los agentes recaudadores o bancos autorizados, a las arcas públicas, poniéndolos a disposición en la cuenta única del Tesoro Nacional, para su uso por parte del Gobierno.')

Percentual Realizado: (58, 'Valor Recaudado/Valor Previsto *100')

Data Lançamento: (61, 'Fecha de registro de la recaudación.')

Exercício: (64, 'Ejercicio al que se refieren los valores.')

Las categorias de recetas corrientes y recetas de capital son:

                      DESCRIÇÃO                                   Unnamed: 3
21   Para Receitas Correntes:                   Para Receitas Correntes:
22                           1.  Impostos, Taxas e Contribuições de Melhoria
23                           2.                                Contribuições
24                           3.                          Receita Patrimonial
25                           4.                         Receita Agropecuária
26                           5.                           Receita Industrial
27                           6.                          Receita de Serviços
28                           7.                     Transferências Correntes
30  Para Receitas de Capital:                  Para Receitas de Capital:
31                           1.                         Operações de Crédito
32                           2.                            Alienação de Bens
33                           3.                   Amortização de Empréstimos
34                           4.                    Transferências de Capital
35                           9.                   Outras Receitas de Capital

In [14]:
df_diccionario_datos.to_pickle("../datos/output/datos_convertido.pkl")